version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=mzd@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - 5050:80

  # app:
  #   container_name: bot
  #   depends_on:
  #     - mongodb
  #   build: ./
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  #   environment:
  #     - DB_HOST=mongodb
  #     - DB_USER=$MONGODB_USER
  #     - DB_PASSWORD=$MONGODB_PASSWORD
  #     - DB_NAME=$MONGODB_DATABASE
  #     - DB_PORT=$MONGODB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true
